dist: xenial
language: java
addons:
  apt:
    packages:
      - ant

matrix:
  include:
  - jdk: oraclejdk9

script:
  - git config --global push.default simple
  - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - ant clean
  - ant compile
  - ant jar
  - ant run


deploy:
  provider: releases
  api_key:
    secure: git@github.com/CS3398-HOUNDS/Assignment-19
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
